/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    'product-images': ProductImage;
    'blog-images': BlogImage;
    products: Product;
    leads: Lead;
    certifications: Certification;
    posts: Post;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'product-images': ProductImagesSelect<false> | ProductImagesSelect<true>;
    'blog-images': BlogImagesSelect<false> | BlogImagesSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    leads: LeadsSelect<false> | LeadsSelect<true>;
    certifications: CertificationsSelect<false> | CertificationsSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  role: 'user' | 'partner' | 'admin';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  caption?: string | null;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-images".
 */
export interface ProductImage {
  id: number;
  alt: string;
  caption?: string | null;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-images".
 */
export interface BlogImage {
  id: number;
  alt: string;
  caption?: string | null;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  title: string;
  /**
   * URL-safe identifier. e.g. natural-cotton-tote-bag
   */
  slug: string;
  /**
   * Internal SKU code. e.g. ZO-TB-001
   */
  sku: string;
  status: 'draft' | 'active' | 'out-of-stock' | 'discontinued';
  /**
   * Show on homepage featured section
   */
  featured?: boolean | null;
  category: 'organic-fabrics' | 'bags' | 'pouches' | 'home-textiles' | 'yoga-wellness' | 'custom-oem';
  /**
   * e.g. "natural dye", "unbleached", "bulk"
   */
  tags?:
    | {
        tag: string;
        id?: string | null;
      }[]
    | null;
  /**
   * One-line shown on product cards (max 160 chars)
   */
  shortDescription: string;
  /**
   * Full product story shown on detail page
   */
  fullDescription?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  featuredImage: number | Media;
  /**
   * Additional product images (packaging, close-ups, in-use)
   */
  gallery?:
    | {
        image: number | Media;
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  specifications: {
    /**
     * e.g. 100% GOTS organic cotton
     */
    material: string;
    /**
     * e.g. 140–180 GSM (or range for customisable)
     */
    gsm?: string | null;
    /**
     * e.g. 38×42 cm
     */
    dimensions?: string | null;
    /**
     * e.g. Natural, Black, custom azo-free dye
     */
    colours?: string | null;
    /**
     * e.g. Unbleached, enzyme-washed, stonewashed
     */
    finish?: string | null;
    /**
     * Any extra spec key-value pairs for the detail table
     */
    additionalSpecs?:
      | {
          label: string;
          value: string;
          id?: string | null;
        }[]
      | null;
  };
  pricing?: {
    currency?: ('USD' | 'EUR' | 'GBP') | null;
    incoterm?: ('FOB' | 'CIF' | 'DDP' | 'EXW') | null;
    /**
     * Port of origin for FOB/CIF pricing
     */
    port?: string | null;
    /**
     * Volume-based pricing. Add tiers from lowest to highest quantity.
     */
    tiers?:
      | {
          minQty: number;
          /**
           * Leave blank for "and above"
           */
          maxQty?: number | null;
          pricePerUnit: number;
          /**
           * e.g. unit, metre, kg
           */
          unit?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  ordering: {
    moq: number;
    /**
     * e.g. units, metres, kg
     */
    moqUnit?: string | null;
    /**
     * e.g. 21–28 days after artwork approval
     */
    leadTimeDays?: string | null;
    sampleAvailable?: boolean | null;
    /**
     * e.g. 5–7 business days
     */
    sampleLeadTime?: string | null;
  };
  /**
   * Link applicable certifications. Manage them in the Certifications collection.
   */
  certifications?: (number | Certification)[] | null;
  customisation?: {
    customLogoAvailable?: boolean | null;
    customSizeAvailable?: boolean | null;
    privateLabelAvailable?: boolean | null;
    customDyeAvailable?: boolean | null;
    /**
     * Any extra details about customisation (shown on detail page)
     */
    customisationNotes?: string | null;
  };
  shipping?: {
    /**
     * Harmonised System code for customs. e.g. 6305.20
     */
    hsCode?: string | null;
    reachCompliant?: boolean | null;
    shippingModes?: ('sea' | 'air' | 'courier')[] | null;
    documentsProvided?: ('commercial-invoice' | 'packing-list' | 'coo' | 'phyto' | 'test-reports' | 'gots-tc')[] | null;
  };
  seo?: {
    /**
     * Defaults to product title if empty
     */
    metaTitle?: string | null;
    /**
     * Max 160 chars. Defaults to shortDescription if empty.
     */
    metaDescription?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "certifications".
 */
export interface Certification {
  id: number;
  /**
   * e.g. GOTS 6.0, OEKO-TEX Standard 100
   */
  name: string;
  /**
   * Badge label shown on product cards. e.g. GOTS, OEKO-TEX
   */
  shortCode: string;
  /**
   * e.g. Control Union, Intertek
   */
  issuingBody?: string | null;
  certificateNumber?: string | null;
  validFrom?: string | null;
  validUntil?: string | null;
  /**
   * PDF of the certificate — downloadable from the product page
   */
  certificateFile?: (number | null) | Media;
  /**
   * One-sentence explanation shown in certification tooltips
   */
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads".
 */
export interface Lead {
  id: number;
  name: string;
  company: string;
  email: string;
  phone?: string | null;
  /**
   * Buyer country — important for export compliance & market tracking
   */
  country?: string | null;
  website?: string | null;
  inquiryType: 'rfq' | 'sample' | 'catalogue' | 'private-label' | 'partnership' | 'general';
  /**
   * Product categories the buyer is interested in
   */
  category?:
    | ('organic-fabrics' | 'bags' | 'pouches' | 'home-textiles' | 'yoga-wellness' | 'custom-oem' | 'other')[]
    | null;
  /**
   * Link specific products they enquired about
   */
  interestedProducts?: (number | Product)[] | null;
  /**
   * e.g. 500 units, 200 metres — free text so buyers can be flexible
   */
  estimatedOrderQty?: string | null;
  /**
   * When does the buyer need the goods?
   */
  targetDeliveryDate?: string | null;
  message: string;
  /**
   * Where did this lead come from?
   */
  source?:
    | ('website' | 'indiamart' | 'alibaba' | 'trade-show' | 'linkedin' | 'referral' | 'email-campaign' | 'other')
    | null;
  /**
   * Auto-filled from URL params if using tracking links
   */
  utmSource?: string | null;
  status: 'new' | 'contacted' | 'sample-sent' | 'negotiating' | 'qualified' | 'won' | 'lost';
  priority?: ('high' | 'medium' | 'low') | null;
  /**
   * Team member handling this lead
   */
  assignedTo?: (number | null) | User;
  /**
   * Schedule next follow-up
   */
  followUpDate?: string | null;
  /**
   * Internal notes — not visible to the buyer
   */
  internalNotes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  /**
   * Auto-generated from title. Edit only if you need a custom URL.
   */
  slug: string;
  status: 'draft' | 'review' | 'published' | 'archived';
  /**
   * Set automatically on first publish. Override if needed.
   */
  publishedAt?: string | null;
  author?: (number | null) | User;
  category:
    | 'export-guides'
    | 'certifications'
    | 'sustainability'
    | 'industry-news'
    | 'supply-chain'
    | 'buyer-resources'
    | 'company-news';
  featured?: boolean | null;
  /**
   * Auto-calculated from content word count on save.
   */
  readingTime?: number | null;
  /**
   * e.g. GOTS, tote bags, EU export, organic cotton
   */
  tags?:
    | {
        tag: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Shown on blog cards and used as meta description. Max 160 characters.
   */
  excerpt: string;
  featuredImage: number | BlogImage;
  /**
   * Describe the image for screen readers and search engines.
   */
  featuredImageAlt: string;
  /**
   * Use H2/H3 headings, bullet lists, and images to structure for SEO.
   */
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Shown in the sidebar. Link products relevant to this post.
   */
  relatedProducts?: (number | Product)[] | null;
  /**
   * Further reading shown at the bottom. Max 2–3 posts.
   */
  relatedPosts?: (number | Post)[] | null;
  seo?: {
    /**
     * Overrides post title in search results. Keep 10–60 chars.
     */
    metaTitle?: string | null;
    /**
     * Overrides excerpt in search results. Keep under 160 chars.
     */
    metaDescription?: string | null;
    /**
     * Only set if this post is republished from another URL.
     */
    canonicalUrl?: string | null;
    /**
     * Use for thin, duplicate, or temporary content only.
     */
    noIndex?: boolean | null;
    /**
     * Primary keyword this post targets. Internal tracking only — not published.
     */
    focusKeyword?: string | null;
    /**
     * Shown on LinkedIn, WhatsApp, Twitter previews. 1200×630px. Falls back to featured image.
     */
    ogImage?: (number | null) | BlogImage;
  };
  /**
   * Controls the JSON-LD structured data injected in the page <head>.
   */
  schema?: {
    /**
     * Article = standard post. HowTo / FAQPage unlock Google rich results.
     */
    articleType?: ('Article' | 'HowTo' | 'FAQPage') | null;
    /**
     * Shown only when type is "FAQ page". Each item becomes a rich result in Google.
     */
    faqItems?:
      | {
          question: string;
          /**
           * Plain text only — no markdown. Keep answers concise.
           */
          answer: string;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'product-images';
        value: number | ProductImage;
      } | null)
    | ({
        relationTo: 'blog-images';
        value: number | BlogImage;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'leads';
        value: number | Lead;
      } | null)
    | ({
        relationTo: 'certifications';
        value: number | Certification;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-images_select".
 */
export interface ProductImagesSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-images_select".
 */
export interface BlogImagesSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  sku?: T;
  status?: T;
  featured?: T;
  category?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  shortDescription?: T;
  fullDescription?: T;
  featuredImage?: T;
  gallery?:
    | T
    | {
        image?: T;
        caption?: T;
        id?: T;
      };
  specifications?:
    | T
    | {
        material?: T;
        gsm?: T;
        dimensions?: T;
        colours?: T;
        finish?: T;
        additionalSpecs?:
          | T
          | {
              label?: T;
              value?: T;
              id?: T;
            };
      };
  pricing?:
    | T
    | {
        currency?: T;
        incoterm?: T;
        port?: T;
        tiers?:
          | T
          | {
              minQty?: T;
              maxQty?: T;
              pricePerUnit?: T;
              unit?: T;
              id?: T;
            };
      };
  ordering?:
    | T
    | {
        moq?: T;
        moqUnit?: T;
        leadTimeDays?: T;
        sampleAvailable?: T;
        sampleLeadTime?: T;
      };
  certifications?: T;
  customisation?:
    | T
    | {
        customLogoAvailable?: T;
        customSizeAvailable?: T;
        privateLabelAvailable?: T;
        customDyeAvailable?: T;
        customisationNotes?: T;
      };
  shipping?:
    | T
    | {
        hsCode?: T;
        reachCompliant?: T;
        shippingModes?: T;
        documentsProvided?: T;
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads_select".
 */
export interface LeadsSelect<T extends boolean = true> {
  name?: T;
  company?: T;
  email?: T;
  phone?: T;
  country?: T;
  website?: T;
  inquiryType?: T;
  category?: T;
  interestedProducts?: T;
  estimatedOrderQty?: T;
  targetDeliveryDate?: T;
  message?: T;
  source?: T;
  utmSource?: T;
  status?: T;
  priority?: T;
  assignedTo?: T;
  followUpDate?: T;
  internalNotes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "certifications_select".
 */
export interface CertificationsSelect<T extends boolean = true> {
  name?: T;
  shortCode?: T;
  issuingBody?: T;
  certificateNumber?: T;
  validFrom?: T;
  validUntil?: T;
  certificateFile?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  status?: T;
  publishedAt?: T;
  author?: T;
  category?: T;
  featured?: T;
  readingTime?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  excerpt?: T;
  featuredImage?: T;
  featuredImageAlt?: T;
  content?: T;
  relatedProducts?: T;
  relatedPosts?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        canonicalUrl?: T;
        noIndex?: T;
        focusKeyword?: T;
        ogImage?: T;
      };
  schema?:
    | T
    | {
        articleType?: T;
        faqItems?:
          | T
          | {
              question?: T;
              answer?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}